In [1]:
import numpy as np

In [2]:
import torch 

In [3]:
array = [[1,2,3],[4,5,6]]
first_array = np.array(array) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


### convert numpy array to tensor

In [4]:
# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x127d4d3b0>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Ones matrix

In [5]:
print("Numpy {}\n".format(np.ones((3,3))))

# pytorch ones
print(torch.ones((3,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### random numbers

In [6]:
print("Numpy {}\n".format(np.random.rand(3,3)))

# pytorch random
print(torch.rand(3,3))

Numpy [[0.2643818  0.2801389  0.61993382]
 [0.07520874 0.91138115 0.18977544]
 [0.27081939 0.66914926 0.81410608]]

tensor([[0.0590, 0.1092, 0.4349],
        [0.1024, 0.7954, 0.7760],
        [0.9646, 0.3970, 0.4708]])


### to & fro conversions

In [7]:
array = np.random.rand(3,2)
print("{} {}\n".format(type(array),array))



<class 'numpy.ndarray'> [[0.48791988 0.55120257]
 [0.75460974 0.15177375]
 [0.66435089 0.44114728]]



In [8]:
# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))



tensor([[0.4879, 0.5512],
        [0.7546, 0.1518],
        [0.6644, 0.4411]], dtype=torch.float64)



In [9]:
# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.48791988 0.55120257]
 [0.75460974 0.15177375]
 [0.66435089 0.44114728]]



In [14]:
import torch      
from torch.autograd import Variable     
import torch.nn as nn 
import warnings

In [15]:
import torchvision

In [ ]:
##http://howieko.com/projects/classifying_flowers_pytorch/
##https://www.kaggle.com/aradhyamathur/flower-classification-pytorch
##https://katba-caroline.com/what-flower-is-this-developing-an-image-classifier-with-deep-learning-using-pytorch/

In [ ]:
#https://medium.com/datadriveninvestor/creating-a-pytorch-image-classifier-da9db139ba80