In [1]:
import numpy as np
import torch

**resizing**

In [3]:
tensor = torch.ones(4,4)
print("\n",tensor)


 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
#Resize
print("{}\n{}".format(tensor.view(16).shape, tensor.view(16)))

torch.Size([16])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


**addition**

In [8]:
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)

print(t1)
print(t2)

print("Addition: \n",t1+t2)
print("Subtraction: \n",t1-t2)
print("Multiplication: \n",t1*t2)
print("Division: \n",t1/t2)

tensor([[0.0073, 0.0016, 0.2248],
        [0.8331, 0.3639, 0.2831]])
tensor([[0.1328, 0.8872, 0.2491],
        [0.9649, 0.7733, 0.1004]])
Addition: 
 tensor([[0.1401, 0.8888, 0.4739],
        [1.7980, 1.1373, 0.3835]])
Subtraction: 
 tensor([[-0.1255, -0.8857, -0.0243],
        [-0.1318, -0.4094,  0.1828]])
Multiplication: 
 tensor([[0.0010, 0.0014, 0.0560],
        [0.8039, 0.2814, 0.0284]])
Division: 
 tensor([[5.4903e-02, 1.7596e-03, 9.0260e-01],
        [8.6339e-01, 4.7058e-01, 2.8207e+00]])


In [10]:
print(t1.add(t2))
print(torch.add(t1, t2))

print(t1.sub(t2))
print(torch.sub(t1, t2))

print(t1.mul(t2))
print(torch.mul(t1, t2))

print(t1.div(t2))
print(torch.div(t1, t2))

tensor([[0.1401, 0.8888, 0.4739],
        [1.7980, 1.1373, 0.3835]])
tensor([[0.1401, 0.8888, 0.4739],
        [1.7980, 1.1373, 0.3835]])
tensor([[-0.1255, -0.8857, -0.0243],
        [-0.1318, -0.4094,  0.1828]])
tensor([[-0.1255, -0.8857, -0.0243],
        [-0.1318, -0.4094,  0.1828]])
tensor([[0.0010, 0.0014, 0.0560],
        [0.8039, 0.2814, 0.0284]])
tensor([[0.0010, 0.0014, 0.0560],
        [0.8039, 0.2814, 0.0284]])
tensor([[5.4903e-02, 1.7596e-03, 9.0260e-01],
        [8.6339e-01, 4.7058e-01, 2.8207e+00]])
tensor([[5.4903e-02, 1.7596e-03, 9.0260e-01],
        [8.6339e-01, 4.7058e-01, 2.8207e+00]])


**average**

In [12]:
print(torch.mean(t1))
print(t1.mean())

tensor(0.2856)
tensor(0.2856)
