In [4]:
import tensorflow as tf
from tensorflow.keras.models import Model

#### Convolution filter

In [5]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(filters=2, kernel_size= 5, strides=(1,1), activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)

(1, 24, 24, 2)


/Users/ankit/Workspace/Projects/ankit-github/AI-ML-DS/54.Deep-Learning-for-Computer-Vision-with-TensorFlow-2/.venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#### Convolution with a filter size as the size of the image

In [6]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(filters=2, kernel_size= 28, strides=(1,1), activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)

(1, 1, 1, 2)


/Users/ankit/Workspace/Projects/ankit-github/AI-ML-DS/54.Deep-Learning-for-Computer-Vision-with-TensorFlow-2/.venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#### Padding "valid"

In [ ]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(filters=2,kernel_size= 5,strides=(1,1), activation='relu', padding="valid", input_shape=input_shape[1:])(x)
print(y.shape)

(1, 24, 24, 2)


In [ ]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(filters=2,kernel_size= 5, strides=(1,1), activation='relu', padding="same", input_shape=input_shape[1:])(x)
print(y.shape)

(1, 28, 28, 2)


In [12]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(filters=2,kernel_size= 5, strides=(1,1),dilation_rate=2, 
                           activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)

(1, 20, 20, 2)


In [13]:
input_shape = (1, 28, 28, 3)
x = tf.random.normal(input_shape)
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1,3,activation='relu',name='conv2d_1',input_shape=input_shape[1:]),
    tf.keras.layers.Conv2D(2,5,activation='relu',name='conv2d_2')
])
output = model(x)
print(output.shape)

/Users/ankit/Workspace/Projects/ankit-github/AI-ML-DS/54.Deep-Learning-for-Computer-Vision-with-TensorFlow-2/.venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


(1, 22, 22, 2)


In [14]:
for layer in model.layers:
    print(layer.name,layer)

conv2d_1 <Conv2D name=conv2d_1, built=True>
conv2d_2 <Conv2D name=conv2d_2, built=True>


In [15]:
model.layers[0].weights

[<Variable path=sequential/conv2d_1/kernel, shape=(3, 3, 3, 1), dtype=float32, value=[[[[-0.20333663]
    [-0.2094566 ]
    [-0.2831943 ]]
 
   [[-0.04246157]
    [-0.04658228]
    [ 0.22654337]]
 
   [[ 0.06912464]
    [ 0.13186526]
    [ 0.09401053]]]
 
 
  [[[-0.22993664]
    [-0.37498364]
    [-0.14681196]]
 
   [[-0.35293293]
    [ 0.18768466]
    [ 0.21168417]]
 
   [[-0.25566688]
    [-0.28607723]
    [ 0.39279354]]]
 
 
  [[[-0.12670392]
    [ 0.23864812]
    [-0.32821357]]
 
   [[-0.35921407]
    [-0.10315746]
    [ 0.4004057 ]]
 
   [[ 0.3794974 ]
    [-0.12970513]
    [-0.14251477]]]]>,
 <Variable path=sequential/conv2d_1/bias, shape=(1,), dtype=float32, value=[0.]>]

In [16]:
model.layers[0].bias.numpy()

array([0.], dtype=float32)

In [17]:
model.layers[0].bias_initializer

In [18]:
model.layers[1].weights

[<Variable path=sequential/conv2d_2/kernel, shape=(5, 5, 1, 2), dtype=float32, value=[[[[-1.3431370e-02  2.1767393e-01]]
 
   [[-2.7990654e-01 -1.9307715e-01]]
 
   [[ 2.1724787e-01  7.5385123e-02]]
 
   [[ 1.5353593e-01 -2.1656495e-01]]
 
   [[-1.7281416e-01  5.0026685e-02]]]
 
 
  [[[-5.4773390e-03 -8.4545508e-02]]
 
   [[-2.1391726e-01 -2.6566973e-01]]
 
   [[-1.5361212e-01  2.6721057e-01]]
 
   [[ 1.2069261e-01  1.9374117e-01]]
 
   [[-5.1347405e-02 -4.5642808e-02]]]
 
 
  [[[ 1.7922783e-01  1.3200825e-01]]
 
   [[ 1.8025094e-01 -1.6362028e-01]]
 
   [[ 4.2498112e-05  1.1848956e-01]]
 
   [[ 2.1524134e-01 -3.2846361e-02]]
 
   [[ 2.7213553e-01  1.4612460e-01]]]
 
 
  [[[ 1.4931449e-01  2.9507935e-02]]
 
   [[-1.7995054e-01 -2.5289628e-01]]
 
   [[ 4.9529761e-02  4.3579042e-02]]
 
   [[ 1.7579409e-01 -2.2865812e-01]]
 
   [[ 1.8210277e-01  1.9367146e-01]]]
 
 
  [[[-1.8999085e-01  8.8689864e-02]]
 
   [[ 1.9091862e-01  1.0503811e-01]]
 
   [[-1.4906855e-01  1.4367193e-01]]
 
   [[ 5

In [19]:
model.weights

[<Variable path=sequential/conv2d_1/kernel, shape=(3, 3, 3, 1), dtype=float32, value=[[[[-0.20333663]
    [-0.2094566 ]
    [-0.2831943 ]]
 
   [[-0.04246157]
    [-0.04658228]
    [ 0.22654337]]
 
   [[ 0.06912464]
    [ 0.13186526]
    [ 0.09401053]]]
 
 
  [[[-0.22993664]
    [-0.37498364]
    [-0.14681196]]
 
   [[-0.35293293]
    [ 0.18768466]
    [ 0.21168417]]
 
   [[-0.25566688]
    [-0.28607723]
    [ 0.39279354]]]
 
 
  [[[-0.12670392]
    [ 0.23864812]
    [-0.32821357]]
 
   [[-0.35921407]
    [-0.10315746]
    [ 0.4004057 ]]
 
   [[ 0.3794974 ]
    [-0.12970513]
    [-0.14251477]]]]>,
 <Variable path=sequential/conv2d_1/bias, shape=(1,), dtype=float32, value=[0.]>,
 <Variable path=sequential/conv2d_2/kernel, shape=(5, 5, 1, 2), dtype=float32, value=[[[[-1.3431370e-02  2.1767393e-01]]
 
   [[-2.7990654e-01 -1.9307715e-01]]
 
   [[ 2.1724787e-01  7.5385123e-02]]
 
   [[ 1.5353593e-01 -2.1656495e-01]]
 
   [[-1.7281416e-01  5.0026685e-02]]]
 
 
  [[[-5.4773390e-03 -8.4545508e

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)               │ (None, 26, 26, 1)      │            28 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 22, 22, 2)      │            52 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 80 (320.00 B)

 Trainable params: 80 (320.00 B)

 Non-trainable params: 0 (0.00 B)